#!/usr/bin/env bash

# Install nginx web server if not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt -y update
    sudo apt install nginx -y
    sudo ufw allow 'Nginx HTTP'
    echo 'Hello World!' > /var/www/html/index.nginx-debian.html
fi

# Add the rewrite rule to the Nginx configuration
redirect_rule="location /redirect_me {
    return 301 https://www.google.com;
}"

# Check if the rule already exists in the config
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default
then
    sudo sed -i "/server_name _;/a $redirect_rule" /etc/nginx/sites-available/default
fi

# Restart Nginx
sudo service nginx restart
